# Используем официальный образ Python
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем requirements.txt в контейнер и устанавливаем зависимости
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Копируем необходимые файлы и директории в контейнер
COPY app.py .
COPY __init__.py .
COPY static/ static/
COPY templates/ templates/

# Открываем порт для приложения
EXPOSE 8000

# Устанавливаем команду для запуска приложения
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]
